ingress:
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: ${cluster_issuer}
  advertisedHost: ${console_domain_name}.${domain_name}
  tlsSecret: ${console_release}-tls-secret

settings:
  edgeControllers:
    - name: Ziti Edge Mgmt API
      url: https://${controller_release}-mgmt.${controller_namespace}.svc:${mgmt_port}
      default: true
